version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    environment:
      - CONNECTION_STRING=###
      - REDIS_URL=###
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

  typescript-frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - FLASK_BACKEND_URL=http://web:5000
    depends_on:
      - web
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - app-network

networks:
  app-network:
    driver: bridge