name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles=24.1.0
  - blinker=1.8.2
  - click=8.1.7
  - colorama=0.4.6
  - dnspython=2.7.0
  - flask=3.0.3
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - hypercorn=0.17.3
  - hyperframe=6.0.1
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - markupsafe=3.0.2
  - numpy=2.1.3
  - packaging=24.1
  - pandas=2.2.3
  - plotly=5.24.1
  - priority=2.0.0
  - prometheus_client=0.21.0
  - pymongo=4.10.1
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - quart=0.19.8
  - redis=5.2.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - six=1.16.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tzdata=2024.2
  - werkzeug=3.1.1
  - wsproto=1.2.0
  - pip
  - pip:
      - aiofiles==24.1.0
