---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: typescript-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typescript-frontend
  template:
    metadata:
      labels:
        app: typescript-frontend
    spec:
      containers:
        - name: typescript-frontend
          image: your-typescript-frontend-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: FLASK_BACKEND_URL
              value: "http://flask-app-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: typescript-frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: typescript-frontend
