cluster:
  enabled: true
  nodeGroup: primary
  replicas: 3
  shardCount: 3

redis:
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
    service:
      port: 6379
      targetPort: 6379
      clusterPort: 7000
      nodePort: 30079
  config: {}

sentinel:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: true
    size: 8Gi
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  service:
    port: 26379
    targetPort: 26379

  config:
    sentinel:
      - "sentinel monitor mymaster redis-master 6379 2"
      - "sentinel down-after-milliseconds mymaster 5000"
      - "sentinel failover-timeout mymaster 10000"
      - "sentinel parallel-syncs mymaster 1"

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"

extraConfigmapMounts:
  - name: redis-conf
    mountPath: /opt/bitnami/redis/etc/redis.conf
    subPath: redis.conf

configMap:
  redis-conf:
    data:
      redis.conf: |
        maxmemory-policy allkeys-lru
        appendonly yes
        appendfsync everysec
        cluster-enabled yes
        cluster-config-file /data/nodes.conf
        cluster-node-timeout 5000
        protected-mode no

